### ISSUE TITLE
typo in email addresses

### ISSUE THREAD

**Issue by howtohumanbetter** [seekhealing/seekhealing.github.io#28]
all the email addresses on http://seekhealing.org/contact.html are incorrect: should be @seekhealing.org, not @seakhealing

**Comment by shredtechular** [comment]
All of the "personal emails" look like they may have been fixed?  Is this still an issue?

The only email on this page that looks like it may be "off" is actually in the footer and it looks like it affects all pages.  The email in the footer says, "info@seekhealing.com" instead of ".org".  Is that correct or does it matter?

<img width="1262" alt="screen shot 2017-10-08 at 3 46 57 pm" src="https://user-images.githubusercontent.com/2396774/31320327-ba47747c-ac40-11e7-971f-cd64fe5183ea.png">
